---
##########################################################
# Install Git
##########################################################

- name: Install Git
  become: yes
  dnf:
    name: git
    state: present

##########################################################
# Verify Git Installation
##########################################################

- name: Check Git Version
  command: git --version
  register: git_version
  changed_when: false

- name: Display Git Version
  debug:
    var: git_version.stdout

##########################################################
# Configure Git Username
##########################################################

- name: Configure Git Username
  command: git config --global user.name "Jenkins"
  become: yes

##########################################################
# Configure Git Email
##########################################################

- name: Configure Git Email
  command: git config --global user.email "jenkins@example.com"
  become: yes

##########################################################
# Verify Git Configuration
##########################################################

- name: Show Git Configuration
  command: git config --global --list
  register: git_config
  changed_when: false

- name: Display Git Configuration
  debug:
    var: git_config.stdout_lines
