- name: Configure Jenkins Server
  hosts: jenkins
  become: yes

  roles:
    - common
    - git
    - java
    - jenkins
    - docker


##########################################################

- name: Configure Web Server
  hosts: web
  become: yes

  roles:
    - common
    - docker
    - nginx
